### PR TITLE
breaking everything

### PR DESCRIPTION
**Pull request by pdh**

### CODE REVIEW

**Comment by skyl** [comment]
Make sure this works on my phone browser

**Comment by skyl** [comment]
Logged in and not logged in

**Comment by pdh** [comment]
hehe, can you try spinning this up locally?

**Comment by pdh** [comment]
btw.. i deleted my chrome profile and simultaneously upgraded; the golden ratio song text magic has been different ever since and it seems it's related to all of my fonts changing.. does it look ok on yours? i've got a workaround in this branch that looks ok to me usually that just removes the multiplier for screen density.

**Comment by skyl** [comment]
Yolo.

**Pull request merged**
